# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

provider:
  name: stackitprivatepreview

data_sources:
  roles:
    read:
      path: /v3alpha1/projects/{projectId}/regions/{region}/instances/{instanceId}/roles
      method: GET
