provider:
  name: stackitprivatepreview

resources:
  database:
    schema:
      attributes:
        aliases:
          id: database_id
    create:
      path: /v3alpha1/projects/{projectId}/regions/{region}/instances/{instanceId}/databases
      method: POST
    read:
      path: /v3alpha1/projects/{projectId}/regions/{region}/instances/{instanceId}/databases/{databaseName}
      method: GET
    delete:
      path: /v3alpha1/projects/{projectId}/regions/{region}/instances/{instanceId}/databases/{databaseName}
      method: DELETE


data_sources:
  databases:
    read:
      path: /v3alpha1/projects/{projectId}/regions/{region}/instances/{instanceId}/databases
      method: GET

  database:
    attributes:
      aliases:
        id: database_id
    read:
      path: /v3alpha1/projects/{projectId}/regions/{region}/instances/{instanceId}/databases/{databaseName}
      method: GET
