# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

provider:
  name: stackitprivatepreview

data_sources:
  version:
    read:
      path: /v3alpha1/projects/{projectId}/regions/{region}/versions
      method: GET
